Set major-mode for org-journal pop-up buffer to org-mode
bastibe/org-journal pull request #415
Opened 2023-08-31 23:53 UTC by drfiresign

Credit to @zhyzky for pinpointing the issue and describing the fix in #414. There's a slightly different macro described in the issue report. I wasn't able to get it working however; I opted instead to just take the solution and modify the existing code as minimally as possible.

I'm happy to let @zhyzky optimize this macro for better performance or simplicity, I just wasn't able to get their solution working in the few minutes I was tinkering with it.

Cheers

2023-09-01 08:08 UTC, zhyzky commented on org-journal.el
> +       (let ((major-mode 'org-mode))
```suggestion
```

2023-09-01 08:15 UTC, zhyzky requested changes
Move the major mode specification inside the setq block, or the major mode won't change in the 'body'. Don't actually know why.
Worked in emacs 28.1

2023-09-01 08:15 UTC, zhyzky commented on org-journal.el
> +         (setq result (progn ,@body))))
```suggestion
         (setq result (let ((major-mode 'org-mode))
                             (progn ,@body))))
```

2023-09-01 08:27 UTC, zhyzky requested changes

2023-09-01 08:27 UTC, zhyzky commented on org-journal.el
> +       (let ((major-mode 'org-mode))
```suggestion
```

2023-09-01 08:27 UTC, zhyzky commented on org-journal.el
> +         (setq result (progn ,@body))))
```suggestion
         (setq result (let ((major-mode 'org-mode))
                             (progn ,@body))))
```

2023-09-01 17:09 UTC, drfiresign commented
Thanks @zhyzky, I appreciate the second set of eyes 👍🏻

2023-09-03 15:11 UTC, bastibe commented
I'm afraid this change might have huge performance impact on searches. We use this function as part of the org-journal-search facilities, and we explicitly search through files in fundamental-mode, as org-mode would make searches extremely slow. For reference, searches often involve hundreds or thousands of files, and org-mode can take up to a second to initialize. That's just not acceptable.

Could you check whether search performance is impacted by this change?

2023-09-04 01:34 UTC, zhyzky commented
> I'm afraid this change might have huge performance impact on searches. We use this function as part of the org-journal-search facilities, and we explicitly search through files in fundamental-mode, as org-mode would make searches extremely slow. For reference, searches often involve hundreds or thousands of files, and org-mode can take up to a second to initialize. That's just not acceptable.
> 
> Could you check whether search performance is impacted by this change?

I understand your concern，and would like to know how to test the search speed.
However, this pull request here would change the major-mode as a variable, that is, it won't interface the font-looking or anything else. So I think it won't slows down the performance, not too much at least I think.

2023-09-04 14:44 UTC, drfiresign commented
> I'm afraid this change might have huge performance impact on searches. We use this function as part of the org-journal-search facilities, and we explicitly search through files in fundamental-mode, as org-mode would make searches extremely slow. For reference, searches often involve hundreds or thousands of files, and org-mode can take up to a second to initialize. That's just not acceptable.

Ah, that is understandable. I definitely think we could use some pointers on how to test this, but I also wonder if you have a better idea on how to deal with [this particular change](https://github.com/emacs-straight/org-mode/commit/f1359546ad7dee9698b75ca25ad453e6f054bd06) in `org-mode` mechanics. If this isn't the right way to approach handling this error, I'd certainly appreciate some advice about how best to avoid this particular disruption.

2023-09-04 15:12 UTC, bastibe commented
To test this, create a journal directory with a few hundred daily files with some random content. The files may contain lorem ipsum, or they may each contain the exact same content, it doesn't matter much. But they should contain some text. Then run an org-journal search on them. And remember that any slowdown encountered on a modern SSD-equipped computer will be infinitely worse on old HDD machines.

I may be wrong. Perhaps org-mode has gotten a lot faster, or uses better caching, and this is no longer an issue. But I remember we coded the org-journal-search specifically in this way, since the regular org-agenda searches were unbearably slow at the time.

As for advice, if I'm reading this correctly, there's an issue with calling org-element-at-point. Essentially, we shouldn't use any org functionality as part of the search. If we do, that's a bug. The whole point of the search (originally) was that it doesn't involve org, and is therefore fast.

If org functionality is required for some uses of org-journal--with-journal, but not searching, then we should create separate functions for these two use cases.

2023-09-05 01:45 UTC, zhyzky commented
> To test this, create a journal directory with a few hundred daily files with some random content. The files may contain lorem ipsum, or they may each contain the exact same content, it doesn't matter much. But they should contain some text. Then run an org-journal search on them. And remember that any slowdown encountered on a modern SSD-equipped computer will be infinitely worse on old HDD machines.

I've got like 34 weeks journal file, and test result like this 
(benchmark-run 10 (org-journal-search-forever "somestring"))
(0.748114 1 0.09099299999999999)   --> original
(0.769555 1 0.09732099999999999)   --> with hack
(0.731607 1 0.08872999999999998)   --> with additional hack
the third result is due to changes like this 
``` lisp
       (setq result (let ((major-mode 'org-mode)
                          (change-major-mode-hook nil))
                      (progn ,@body))))
```
So the performance reduce by this hack is accepable, right?

> I may be wrong. Perhaps org-mode has gotten a lot faster, or uses better caching, and this is no longer an issue. But I remember we coded the org-journal-search specifically in this way, since the regular org-agenda searches were unbearably slow at the time.
> 
> As for advice, if I'm reading this correctly, there's an issue with calling org-element-at-point. Essentially, we shouldn't use any org functionality as part of the search. If we do, that's a bug. The whole point of the search (originally) was that it doesn't involve org, and is therefore fast.
> 
> If org functionality is required for some uses of org-journal--with-journal, but not searching, then we should create separate functions for these two use cases.

Now I get your point why to design a journal mode, that is to use the org-mode to edit (a) journal file while to search (several) files under fundamental mode, right? That would be a more complex project.

2023-09-05 19:10 UTC, bastibe commented
Fascinating! Utterly fascinating! 

I remember how searching used to take minutes with org-mode enabled, and less than a second with it disabled. I ran the benchmark on my machine as well, on my 1200-file journal, and I can confirm that the performance impact is negligible.

Could it be that `(setq major-mode 'org-mode)` is not actually activating org-mode, but is still fixing the warning somehow?

At any rate, I have no further reservations about this change. Sorry for the confusion.

2023-09-05 19:33 UTC, drfiresign commented
Great! @zhyzky you did all the work here I just tried to make the PR, did you want to open a separate PR for this or use the Suggestion feature to add `change-major-mode-hook`?

2023-09-06 01:25 UTC, zhyzky commented
> Could it be that `(setq major-mode 'org-mode)` is not actually activating org-mode, but is still fixing the warning somehow?

The main reason here is to use a (let) structure, where a temperary variable named 'major-mode' is defined inside the block. Not the (setq), which would change the major-mode(globally) and would cause the actual function (org-mode) to run.
And the 'change-major-mode-hook' the same. 
I was just guessing that even for (let) would somehow invoke the 'change-major-mode-hook', so I give it a try.
@bastibe If you're happy with this patch, could you please just modified the code when you approve the pull request?

2023-09-10 09:38 UTC, bastibe commented on org-journal.el
> +       (setq result (let ((major-mode 'org-mode))
Please add a comment describing the reason for this, and mentioning that it does not activate org-mode.

2023-09-10 09:38 UTC, bastibe commented
I would ask you to add a comment that describes the reason for the `let` at this point in the code. After that, I'll happily merge it.

2023-10-05 19:33 UTC, nuthub commented
I'd love to see this patch merged into the main branch. For me it just works. Is the pull request stuck because of the missing comment?

2023-10-06 15:33 UTC, bastibe commented
Yes, actually. Feel free to open a new pull request and add the missing comment, and I'll merge that one.

2023-10-06 16:29 UTC, drfiresign commented
Hi folks, sorry for the delay here; I've updated the change with a brief comment. Let me know it this is unacceptable for any reason.

2023-10-07 07:57 UTC, bastibe commented
No worries! Looks good from my end. Is this ready to merge?

2023-10-09 18:02 UTC, drfiresign commented
@bastibe Yes, this is ready as far as I'm concerned 👍🏻 Thanks for your help!

2023-10-13 11:47 UTC, merged

2023-10-21 08:11 UTC, nuthub commented
thank you!